version: '3.9'

services:
  app:
    container_name: wallet-api
    image: springboot-mysql
    ports:
      - "8095:8095"
    build:
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql-db
    image: 'mysql/mysql-server:5.7'
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    restart: always