version: '3.9'

services:
  app:
    container_name: wallet-api
    image: springboot-postgresql
    build: ./
    ports:
      - "8095:8095"
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresqldb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgresqldb
